### ISSUE TITLE
Any Example code to produce your paper figures ?

### ISSUE THREAD

**Issue by mamun41** [theorod93/sCCA#1]
Dear Author, 

Thank you so much for your great work and for making the repository available.
Can you share an example script to run and combined your repository codes?
This will be more convenient for a user like me.

Best regards,
Mamun

**Comment by theorod93** [comment]
Hi Mamun, 

Apologies for the very late response and thank you for raising this issue. 
I have included a script under the Functions directory with the three sCCA algorithms applied on a simple example. Please let me know if you have any further issues.

Kind regards, 
Theo
